# Generated by Django 6.0.3 on 2026-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=0, max_length=20),
        ),
    ]
