# Generated by Django 6.0.3 on 2026-03-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='draft', max_length=20),
        ),
    ]
